# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField(default=0, null=True)),
                ('txt_field', models.CharField(blank=True, max_length=256)),
                ('bool_field', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('start_registration', models.DateTimeField()),
                ('end_registration', models.DateTimeField()),
                ('description', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('email_template', models.TextField(help_text='Enkele placeholders: {{voornaam}}, {{achternaam}}, {{inschrijf_opties}}')),
                ('price', models.IntegerField(default=0, help_text='Eurocenten')),
                ('max_registrations', models.IntegerField(default=0, help_text='Als groter dan 0, bepaalt maximaal aantal inschrijvingen')),
            ],
            options={
                'ordering': ('-end_registration',),
            },
        ),
        migrations.CreateModel(
            name='EventOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField(default=0, help_text='Eurocenten')),
                ('active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('limit', models.IntegerField(default=0, help_text='Aantal beschikbare plekken (0 = geen limiet)')),
            ],
        ),
        migrations.CreateModel(
            name='EventQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('question_type', models.CharField(choices=[('INT', 'Integer'), ('TXT', 'Text Input'), ('AFD', 'Afdeling'), ('BOOL', 'Ja/Nee'), ('CHOICE', 'Multiple Choice'), ('TEXT', 'HTML Text')], max_length=16)),
                ('required', models.BooleanField(default=False, help_text='Bij Ja/Nee: verplicht aanvinken; bij andere: verplicht invullen')),
                ('radio', models.BooleanField(default=False, help_text='Voor multiple-choice/afdeling: geen dropdown maar radio buttons')),
                ('order', models.IntegerField(default=0, help_text='Bepaalt volgorde op formulier; gebruik order<0 voor elementen vooraf aan voornaam, achternaam en email')),
                ('text', models.TextField(blank=True, default='', help_text='Voor "HTML Text"; geldige HTML tags: a, b/strong, code, em/i, h3, img, ul, ol, li, p, br; Geldige HTML attributen: class, style, a.href, a.target, img.src, img.alt')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('price', models.IntegerField(default=0)),
                ('payed', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('trxid', models.CharField(blank=True, default='', max_length=128)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='subscribe.Event')),
            ],
        ),
        migrations.AddField(
            model_name='eventoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='subscribe.EventQuestion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='option',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='subscribe.EventOption'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscribe.EventQuestion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='subscribe.Registration'),
        ),
    ]
