# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-20 22:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='payed',
            new_name='paid',
        ),
    ]
