# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def copy_payments(apps, schema_editor):
    Registration = apps.get_model("subscribe", "Registration")
    Payment = apps.get_model("subscribe", "Payment")
    for reg in Registration.objects.all():
        if reg.trxid != "":
            p = Payment(trxid=reg.trxid, url="", status=reg.status, paid=reg.paid, time=reg.registration_date, price=reg.price)
            p.registration = reg
            p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_renamed_paid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trxid', models.CharField(max_length=128)),
                ('price', models.IntegerField(default=0)),
                ('url', models.CharField(blank=True, max_length=254)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, max_length=64)),
                ('paid', models.BooleanField(default=False)),
                ('data', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='subscribe.Registration'),
        ),
        migrations.RunPython(copy_payments),
        migrations.RemoveField(
            model_name='registration',
            name='status',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='trxid',
        ),
    ]
